FROM alpine:3.20

RUN apk add --no-cache bash curl jq unzip ca-certificates coreutils openssl

# Bootstrap-Script ins Image
COPY bootstrap.sh /usr/local/bin/bootstrap.sh
RUN chmod +x /usr/local/bin/bootstrap.sh

ENTRYPOINT ["/usr/local/bin/bootstrap.sh"]
