services:
  redis:
    container_name: ${CONTAINER_NAME_PREFIX}-redis
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - ./redis:/data
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --save ""
      --tcp-backlog 128
      --timeout 300
      --tcp-keepalive 60
      --databases 1
      --hz 10
      --loglevel warning
      --client-output-buffer-limit "normal 0 0 0"
      --stop-writes-on-bgsave-error no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 15s
    networks:
      - default

  ghost:
    container_name: ${CONTAINER_NAME_PREFIX}-ghost
    image: ghost:latest
    build: . 
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      NODE_ENV: production
      url: https://${HOSTNAME}
      # Mail
      mail__transport: ${GHOST_MAIL_TRANSPORT}
      mail__from: ${GHOST_MAIL_FROM}
      mail__options__service: ${GHOST_MAIL_SERVICE}
      mail__options__host: ${GHOST_MAIL_HOST}
      mail__options__port: ${GHOST_MAIL_PORT}
      mail__options__auth__user: ${GHOST_MAIL_USER}
      mail__options__auth__pass: ${GHOST_MAIL_PASS}
      # Redis-Cache
      cache__type: ${GHOST_CACHE_TYPE}
      cache__redis__host: ${GHOST_CACHE_REDIS_HOST}
      cache__redis__port: ${GHOST_CACHE_REDIS_PORT}
      cache__redis__db: ${GHOST_CACHE_REDIS_DB}
      cache__redis__keyPrefix: ${GHOST_CACHE_REDIS_KEYPREFIX}
      cache__redis__ttl: ${GHOST_CACHE_REDIS_TTL}
      cache__redis__reuseConnection: ${GHOST_CACHE_REDIS_REUSECONNECTION}
      cache__redis__refreshAheadFactor: ${GHOST_CACHE_REDIS_REFRESHAHEADFACTOR}
      cache__redis__getTimeoutMilliseconds: ${GHOST_CACHE_REDIS_GETTIMEOUTMS}
      cache__redis__storeConfig__retryConnectSeconds: ${GHOST_CACHE_REDIS_RETRYCONNECTSECONDS}
      cache__redis__storeConfig__lazyConnect: ${GHOST_CACHE_REDIS_LAZYCONNECT}
      cache__redis__storeConfig__enableOfflineQueue: ${GHOST_CACHE_REDIS_ENABLEOFFLINEQUEUE}
      cache__redis__storeConfig__maxRetriesPerRequest: ${GHOST_CACHE_REDIS_MAXRETRIES}
      # HostSettings
      hostSettings__postsPublicCache__enabled: "true"
      hostSettings__linkRedirectsPublicCache__enabled: "true"
    volumes:
      - ./content:/var/lib/ghost/content
      - ./bootstrap:/var/lib/ghost/content/bootstrap
      - ./config.production.json:/var/lib/ghost/config.production.json:ro
    networks:
      - default
      - proxy
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/2368' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    labels:
      - "traefik.enable=true"
      # HTTP => HTTPS redirect
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-ghost-insecure.rule=Host(`${HOSTNAME}`) && !PathPrefix(`/proxy/`)"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-ghost-insecure.entrypoints=http"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-ghost-insecure.service=${CONTAINER_NAME_PREFIX}-ghost"
      - "traefik.http.middlewares.${CONTAINER_NAME_PREFIX}-redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.${CONTAINER_NAME_PREFIX}-redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-ghost-insecure.priority=80"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-ghost-insecure.middlewares=${CONTAINER_NAME_PREFIX}-redirect-to-https"

      # HTTPS Ghost
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-ghost.rule=Host(`${HOSTNAME}`) && !PathPrefix(`/proxy/`)"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-ghost.entrypoints=https"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-ghost.service=${CONTAINER_NAME_PREFIX}-ghost"
      - "traefik.http.services.${CONTAINER_NAME_PREFIX}-ghost.loadbalancer.server.port=2368"
      - "traefik.http.services.${CONTAINER_NAME_PREFIX}-ghost.loadbalancer.passhostheader=true"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-ghost.tls=true"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-ghost.tls.certresolver=http"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-ghost.priority=90"

      # ActivityPub HTTPS passthrough
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-ghost-activitypub.rule=Host(`${HOSTNAME}`) && (PathPrefix(`/.ghost/activitypub/`)) || (Host(`${HOSTNAME}`) && PathPrefix(`/.well-known/webfinger`)) || (Host(`${HOSTNAME}`) && PathPrefix(`/.well-known/nodeinfo`))"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-ghost-activitypub.entrypoints=https"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-ghost-activitypub.service=${CONTAINER_NAME_PREFIX}-ghost-activitypub"
      - "traefik.http.services.${CONTAINER_NAME_PREFIX}-ghost-activitypub.loadbalancer.server.url=https://ap.ghost.org"
      - "traefik.http.services.${CONTAINER_NAME_PREFIX}-ghost-activitypub.loadbalancer.passhostheader=true"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-ghost-activitypub.tls=true"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-ghost-activitypub.tls.certresolver=http"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-ghost-activitypub.priority=100"
      - "traefik.docker.network=proxy"

  nginx:
    container_name: ${CONTAINER_NAME_PREFIX}-nginx
    image: nginx:alpine
    depends_on:
      ghost:
        condition: service_started
    restart: unless-stopped
    volumes:
      - ./nginx-proxy.traefik.conf:/etc/nginx/nginx.conf:ro
      - nginx-cache:/var/cache/nginx
    networks:
      - default
      - proxy
    healthcheck:
      test: curl --fail http://localhost/proxy/npm/@tryghost/sodo-search@latest/umd/sodo-search.min.js || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-nginx.rule=Host(`${HOSTNAME}`) && PathPrefix(`/proxy/`)"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-nginx.entrypoints=https"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-nginx.tls=true"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-nginx.tls.certresolver=http"
      - "traefik.http.services.${CONTAINER_NAME_PREFIX}-nginx.loadbalancer.server.port=80"
      - "traefik.http.services.${CONTAINER_NAME_PREFIX}-nginx.loadbalancer.passhostheader=true"
      - "traefik.http.routers.${CONTAINER_NAME_PREFIX}-nginx.priority=95"
      - "traefik.docker.network=proxy"

volumes:
  nginx-cache:

networks:
  default:
    driver: bridge
  proxy:
    external: true
